#!/usr/bin/env bash
# Wrapper invoked by every Claude Code hook event. Plugin-level hooks
# (PreToolUse) get CLAUDE_PLUGIN_DATA injected by Claude Code;
# skill-scoped hooks (Stop, PostToolUse defined inside SKILL.md frontmatter) do
# not. When CLAUDE_PLUGIN_DATA is missing, fall back to the standard plugin
# data directory under ~/.claude/plugins/data/.
if [ -z "${CLAUDE_PLUGIN_DATA}" ]; then
    for candidate in "${HOME}/.claude/plugins/data"/*clover*; do
        if [ -d "${candidate}" ]; then
            export CLAUDE_PLUGIN_DATA="${candidate}"
            break
        fi
    done
fi

# Self-bootstrap. If the plugin was enabled (or updated) mid-session,
# SessionStart never fired with the plugin loaded, so setup.sh never ran
# and the binary was never deployed — making every hook event silently
# no-op. Run setup.sh on demand whenever the deployed binary is missing or
# is not exactly the version this clone ships.
#
# The exact-match test (rather than "is it older?") also repairs machines
# left ahead of the clone by the runtime self-update we used to perform:
# those need to come back down to the pinned version. setup.sh is cheap on
# this path — a version-file read when nothing changed, a cp at worst — and
# never touches the network.
BINARY="${CLAUDE_PLUGIN_DATA}/bin/clover-hook"
VERSION_FILE="${CLAUDE_PLUGIN_DATA}/bin/.version"
CLONE_VERSION=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/plugin.json" 2>/dev/null | grep -o '[0-9][0-9.]*')
DEPLOYED_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "")

# The CLONE_VERSION guard keeps an unreadable plugin.json from re-running
# setup.sh on every single hook fire.
if [ ! -x "$BINARY" ] || { [ -n "$CLONE_VERSION" ] && [ "$DEPLOYED_VERSION" != "$CLONE_VERSION" ]; }; then
    bash "${CLAUDE_PLUGIN_ROOT}/scripts/setup.sh"
fi

# shellcheck source=/dev/null  # runtime-generated by setup.sh; not present at lint time
. "${CLAUDE_PLUGIN_DATA}/env.sh" 2>/dev/null
exec "$BINARY" "$@"
