#!/usr/bin/env bash
# Wrapper invoked by every Claude Code hook event. Plugin-level hooks
# (UserPromptSubmit, PreToolUse) get CLAUDE_PLUGIN_DATA injected by Claude Code;
# skill-scoped hooks (Stop, PostToolUse defined inside SKILL.md frontmatter) do
# not. When CLAUDE_PLUGIN_DATA is missing, fall back to the standard plugin
# data directory under ~/.claude/plugins/data/.
if [ -z "${CLAUDE_PLUGIN_DATA}" ]; then
    for candidate in "${HOME}/.claude/plugins/data"/*clover*; do
        if [ -d "${candidate}" ]; then
            export CLAUDE_PLUGIN_DATA="${candidate}"
            break
        fi
    done
fi

# Self-bootstrap. If the plugin was enabled (or auto-updated) mid-session,
# SessionStart never fired with the plugin loaded, so setup.sh never ran
# and the binary was never deployed — making every hook event silently
# no-op. Run setup.sh on demand whenever the binary is missing or behind the
# clone's bundled version.
#
# This is the latency-sensitive path (UserPromptSubmit fires on every prompt),
# so we call setup.sh with --no-update: it never touches the network here and
# only deploys the bundled binary. Network-backed auto-update happens on the
# SessionStart path. We also never trigger when the deployed binary is *ahead*
# of the clone (i.e. it self-updated to a newer release) — that's not stale.
BINARY="${CLAUDE_PLUGIN_DATA}/bin/clover-hook"
VERSION_FILE="${CLAUDE_PLUGIN_DATA}/bin/.version"
CLONE_VERSION=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "${CLAUDE_PLUGIN_ROOT}/.claude-plugin/plugin.json" 2>/dev/null | grep -o '[0-9][0-9.]*')
DEPLOYED_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "")

# True (0) when $1 (deployed) is strictly older than $2 (clone). Pure bash
# so it matches setup.sh's comparison and works on macOS's bash 3.2.
is_behind() {
    [ -z "$2" ] && return 1
    [ -z "$1" ] && return 0
    [ "$1" = "$2" ] && return 1
    local i n; local -a a b
    IFS=. read -ra a <<< "$1"
    IFS=. read -ra b <<< "$2"
    n=${#a[@]}; [ ${#b[@]} -gt "$n" ] && n=${#b[@]}
    for (( i = 0; i < n; i++ )); do
        local x=${a[i]:-0} y=${b[i]:-0}
        if [ "$x" -gt "$y" ] 2>/dev/null; then return 1; fi
        if [ "$x" -lt "$y" ] 2>/dev/null; then return 0; fi
    done
    return 1
}

if [ ! -x "$BINARY" ] || is_behind "$DEPLOYED_VERSION" "$CLONE_VERSION"; then
    bash "${CLAUDE_PLUGIN_ROOT}/scripts/setup.sh" --no-update
fi

# Registry self-heal trigger. For users stuck in split-brain state
# (installed_plugins.json missing the clover entry), the SessionStart
# hook never fires for the plugin, so setup.sh never runs, so the
# self-heal block inside setup.sh — which would write the missing
# entry — is unreachable. This is the only execution path that DOES
# fire in that state, because Claude Code's hook dispatch keeps
# routing through the deployed binary path. setup.sh is fully
# idempotent — its self-heal block is a no-op on machines where the
# registry entry already exists and is valid. See the matching block
# in setup.sh and its TODO(clover-coding-plugin) for removal criteria.
REGISTRY="${HOME}/.claude/plugins/installed_plugins.json"
if [ ! -f "$REGISTRY" ] || ! grep -q '"clover@clover-security"' "$REGISTRY" 2>/dev/null; then
    bash "${CLAUDE_PLUGIN_ROOT}/scripts/setup.sh" >/dev/null 2>&1 || true
fi

# shellcheck source=/dev/null  # runtime-generated by setup.sh; not present at lint time
. "${CLAUDE_PLUGIN_DATA}/env.sh" 2>/dev/null
exec "$BINARY" "$@"
